export const TOOLS = [
  {
    id: 'merge-pdf',
    name: 'Merge PDFs',
    description: 'Combine multiple PDF files into one document.',
    icon: '📎',
    accept: ['pdf'],
    multiple: true,
    reorderable: true,
    endpoint: '/pdf/merge',
    inputLabel: 'Drop your PDF files here',
    fileField: 'files',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract a range of pages from a PDF.',
    icon: '✂️',
    accept: ['pdf'],
    multiple: false,
    endpoint: '/pdf/split',
    inputLabel: 'Drop your PDF here',
    fileField: 'file',
    extraFields: [
      { name: 'start_page', label: 'Start page', type: 'number', default: 1 },
      { name: 'end_page', label: 'End page', type: 'number', default: '' },
    ],
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce the file size of your PDF.',
    icon: '🗜️',
    accept: ['pdf'],
    multiple: false,
    endpoint: '/pdf/compress',
    inputLabel: 'Drop your PDF here',
    fileField: 'file',
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    description: 'Convert JPG or PNG images into a single PDF.',
    icon: '🖼️',
    accept: ['jpg', 'jpeg', 'png', 'webp'],
    multiple: true,
    endpoint: '/pdf/images-to-pdf',
    inputLabel: 'Drop your images here',
    fileField: 'files',
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to images',
    description: 'Convert each page of a PDF into a PNG image.',
    icon: '📸',
    accept: ['pdf'],
    multiple: false,
    endpoint: '/convert/pdf-to-images',
    inputLabel: 'Drop your PDF here',
    fileField: 'file',
    outputZip: true,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert a Word document (.docx) to PDF.',
    icon: '📝',
    accept: ['docx'],
    multiple: false,
    endpoint: '/convert/word-to-pdf',
    inputLabel: 'Drop your Word document here',
    fileField: 'file',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert a PDF into an editable Word document.',
    icon: '📄',
    accept: ['pdf'],
    multiple: false,
    endpoint: '/convert/pdf-to-word',
    inputLabel: 'Drop your PDF here',
    fileField: 'file',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate all pages in a PDF by 90, 180 or 270 degrees.',
    icon: '🔃',
    accept: ['pdf'],
    multiple: false,
    endpoint: '/convert/rotate-pdf',
    inputLabel: 'Drop your PDF here',
    fileField: 'file',
    extraFields: [
      {
        name: 'rotation',
        label: 'Rotation',
        type: 'select',
        options: ['90', '180', '270'],
        default: '90',
      },
    ],
  },
  {
    id: 'resize-image',
    name: 'Resize image',
    description: 'Resize an image by width, height or both. Aspect ratio preserved if only one is set.',
    icon: '↔️',
    accept: ['jpg', 'jpeg', 'png', 'webp'],
    multiple: false,
    endpoint: '/convert/resize-image',
    inputLabel: 'Drop your image here',
    fileField: 'file',
    extraFields: [
      { name: 'width', label: 'Width (px)', type: 'number', default: '' },
      { name: 'height', label: 'Height (px)', type: 'number', default: '' },
    ],
  },
]